modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="binar"
description='''
A standalone NeoForge factions system with weighted core and border territory, relation-aware tags, and JourneyMap overlays.
'''

[[mixins]]
config="terrafactions.create.mixins.json"
requiredMods=["create"]

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="terralib"
type="required"
versionRange="[${terralib_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="journeymap"
type="optional"
versionRange="[1.21.1-6.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="optional"
versionRange="[6.0.0,7.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="toroidal_world"
type="optional"
versionRange="[0.16.8,)"
ordering="AFTER"
side="BOTH"
